### PR TITLE
misc bugs 4

### PR DESCRIPTION
**Pull request by TateB**
fixed:
- wrong emoji on windows #114 
- header buttons behaviour on search focus

### CODE REVIEW

**Review by LeonmanRolls — CHANGES_REQUESTED** [review]
Add test for the hidden header buttons

**Comment by TateB** [comment]
> Add test for the hidden header buttons

@LeonmanRolls wasn't the concept to test for the bugs? if so, the header buttons being hidden was never the bug here

**Comment by LeonmanRolls** [comment]
> > Add test for the hidden header buttons
> 
> 
> 
> @LeonmanRolls wasn't the concept to test for the bugs? if so, the header buttons being hidden was never the bug here

It came up as a bug because one would click the search bar and then the buttons would disappear, but the search bar didn't expand to take up the space.

**Comment by TateB** [comment]
> It came up as a bug because one would click the search bar and then the buttons would disappear, but the search bar didn't expand to take up the space.

@LeonmanRolls wouldn't that mean that i want to test for the search bar expanding then?

**Comment by LeonmanRolls** [comment]
> > It came up as a bug because one would click the search bar and then the buttons would disappear, but the search bar didn't expand to take up the space.
> 
> @LeonmanRolls wouldn't that mean that i want to test for the search bar expanding then?

Yes that's a more accurate way to say it

**Review by LeonmanRolls — APPROVED** [review]

**Pull request merged**
