### PR TITLE
fix: misc bugs 6

### PR DESCRIPTION
**Pull request by TateB**
fixed:
- FET-955: searching for emojis hangs profile page (not locally, only on cloudflare)
  - test: cypress/stateful/profile
- FET-957: background for transparent avatar uploads is black instead of white
  - test: N/A for now, full testing for avatar uploads to be implemented later
- FET-945: continue button in transaction toasts
  - test: cypress/stateless/registerName
- FET-967: primary name flow resumable even if only 1 tx
  - test: cypress/stateless/setPrimary
- FET-961: create subname + unknown labels flow allows dot in middle of input
  - test: unit/useValidateSubnameLabel
- FET-953: token section in more tab is shown for any .eth subname
  - added: ownership section is always shown in more tab, even if name is not owned
  - test: unit/MoreTab
- FET-935: "I'd like to setup my profile first" button in registration is black and regular weight instead of blue/bold
  - test: cypress/stateless/reigsterName
- FET-943: PCC expired subnames show "delete subname" button but not actually possible
  - test: cypress/stateless/deleteSubname
- FET-959: two close icons in "Add profile fields" dialog
  - test: N/A, can't really test for an unexpected scenario like this
- FET-958: Add profile fields dialog search does not behave correctly, e.g. searching for website does not yield website record result nor contenthash results
  - test: unit/AddProfileRecordView

### CODE REVIEW

**Comment by jefflau** [comment]
@TateB Can you expand on the bugs in the following format:

Bug:
Replication details:
Resolution details:  (Can skip if not different to replication)
Device/OS:

**Comment by TateB** [comment]
@jefflau added references to corresponding linear tickets + expanded on bugs in linear

**Review by LeonmanRolls — CHANGES_REQUESTED** [review]
Add tests

**Comment by jefflau** [comment]
- [ ] FET-955: searching for emojis hangs profile page (not locally, only on cloudflare)
- [ ] test: cypress/stateful/profile
- [ ] FET-957: background for transparent avatar uploads is black instead of white
- [ ] test: N/A for now, full testing for avatar uploads to be implemented later
- [ ] FET-945: continue button in transaction toasts
- [ ] test: cypress/stateless/registerName
- [ ] FET-967: primary name flow resumable even if only 1 tx
- [ ] test: cypress/stateless/setPrimary
- [ ] FET-961: create subname + unknown labels flow allows dot in middle of input
- [ ] test: unit/useValidateSubnameLabel
- [ ] FET-953: token section in more tab is shown for any .eth subname
- [ ] added: ownership section is always shown in more tab, even if name is not owned
- [ ] test: unit/MoreTab
- [ ] FET-935: "I'd like to setup my profile first" button in registration is black and regular weight instead of blue/bold
- [ ] test: cypress/stateless/reigsterName
- [ ] FET-943: PCC expired subnames show "delete subname" button but not actually possible
- [ ] test: cypress/stateless/deleteSubname
- [ ] FET-959: two close icons in "Add profile fields" dialog
- [ ] test: N/A, can't really test for an unexpected scenario like this
- [ ] FET-958: Add profile fields dialog search does not behave correctly, e.g. searching for website does not yield website record result nor contenthash results
- [ ] test: unit/AddProfileRecordView

Adding as a checklist to check bugs

**Review by LeonmanRolls — APPROVED** [review]

**Pull request merged**
